name: Setup NEXTRIQ Discord v3
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install requests
      - run: python3 nextriq_discord_v3-2.py
        env:
          BOT_TOKEN: ${{ secrets.NEXTRIQ_BOT }}
          SERVER_ID: ${{ secrets.SERVER_ID }}
